name: Run Level 8
on: [push, pull_request]
jobs:
  level8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run original
        run: |
          cd Level8Binaries
          chmod +x block.bin
          yes | sudo ./block.bin
      - name: Run modified
        run: |
          chmod +x block-changed.bin
          yes | sudo ./block-changed.bin
