name: Run Level 8
on: [push, pull_request]
jobs:
  level8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd Level8Binaries
          chmod +x block.bin
          chown root:root -R ~
          yes | sudo ./block.bin
