name: Run Level 8
on: [push, pull_request]
jobs:
  level8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x block.bin
          y | ./block.bin
